# @package _global_
dataset:
  name: bank
  path: ../data/bank
  intent_info_path: ../data/bank/intent_info
  description_type: d1_pattern
  uttr_len: 80
  desc_len: 25

experiment:
  intent_desc_first: false
  epochs: 7
  batch_size: 8
  accum_steps: 2
  seed: 0
  temperature: 0.5
  k_negative: 7
  mlm_percent: 0.2
  embedding_param: 0.3
  mlm_param: 1

scheduler:
  lr: 5e-5
  warmup_steps: 0.15