# @package _global_
dataset:
  name: clinc
  path: ../data/clinc
  intent_info_path: ../data/clinc/intent_info
  description_type: d1_pattern
  uttr_len: 20
  desc_len: 15

experiment:
  intent_desc_first: c
  epochs: 20
  batch_size: 8
  accum_steps: 2
  seed: 0
  temperature: 0.5
  k_negative: 7
  mlm_percent: 0.2
  embedding_param: 0.3
  mlm_param: 1

scheduler:
  lr: 2e-5
  warmup_steps: 0.15